services:
  hub:
    build: .
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    depends_on:
      - db
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: 1234
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_volume:
