services:
  hub:
    hostname: hub
    container_name: hub
    build: .
    depends_on:
      db:
        condition: service_healthy

  mosquitto:
    hostname: broker
    container_name: broker
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    depends_on:
      - db
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  db:
    hostname: db
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: 1234
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U db_admin"]
      start_period: 5s
      interval: 10s
      retries: 3
      timeout: 5s

volumes:
  db_volume:
